CREATE TABLE AEM_MIGRATION(
    IDENT INTEGER,
    NAME VARCHAR(100)
);
INSERT INTO AEM_MIGRATION(IDENT, NAME) VALUES(1,'LALALA LALALALA');
INSERT INTO AEM_MIGRATION(IDENT, NAME) VALUES(2,'LULULULU ');
INSERT INTO AEM_MIGRATION(IDENT, NAME) VALUES(3,'LOLOLO');
COMMIT;